public static class HomeGuideContent
{
    public const int Count=6;
    private static string T(string tr,string en)=>GameContentCopy.Text(tr,en);
    public static string Title(int page)
    {
        switch(page){
            case 0:return T("Birlikte ilk adımlar","Your first steps together");
            case 1:return T("Bakım küçük bir alışkanlık","A little daily care");
            case 2:return T("Her eşyanın bir yeri var","A place for everything");
            case 3:return T("Kedinle sohbet et","Spend time with your cat");
            case 4:return T("Sokağa çık, oyuna katıl","A little adventure");
            default:return T("Yuvan güvende kalsın","Look after your home");}
    }
    public static string Body(int page)
    {
        switch(page){
            case 0:return T("HAREKET\nSol alttaki analog kontrolü sürükle. Az itince normal yürür, daha uzağa itince koşar. Bırakınca durur.\n\nSEVGİ\nKedinin üzerinde nazikçe parmağını gezdir. Menü açıkken odadaki hareketler bekler.","MOVEMENT\nDrag the joystick at the bottom left. A small push walks; a full push runs. Release to stop.\n\nAFFECTION\nGently stroke your cat. Room controls wait while a menu is open.");
            case 1:return T("MAMA VE SU\nKabın açık ön tarafına yaklaş. Sağda çıkan Mama ye veya Su iç düğmesine dokun. Düğme yalnız gerçek eşyanın yanında görünür. Tok veya susamamış kedi ihtiyacını söyler.\n\nDİNLENME\nYatağa veya dinlenme eşyasına yaklaş ve eylemi seç. Enerji yavaşça dolar. Bitirmek için Uyan veya Kalk düğmesine dokun.","FOOD AND WATER\nApproach the open front of a bowl and tap Eat or Drink on the right. Actions appear beside real furniture. A full cat will tell you it is not hungry or thirsty.\n\nREST\nApproach a bed or resting spot and choose its action. Energy recovers gradually. Tap Wake up or Get up when you are ready.");
            case 2:return T("MAĞAZA VE ODALAR\nAlt şeritten mağazayı ve oda seçimini aç. Her oda kendi mobilyalarını kullanır; satın alınan ürünler ayrılmış yerlerine gelir.\n\nOYUNCAK KOLEKSİYONU\nKedi oyuncakları salonda durur: aynı anda en fazla 5 eşya ve 1 yatak. Kaldır seçeneği eşyayı koleksiyona alır; tekrar satın almadan Odaya ekle ile geri getirebilirsin.\n\nETKİLEŞİM\nEşyanın açık girişine yaklaş. Uzaktan eşyaya dokunmak kediyi ışınlamaz.","SHOP AND ROOMS\nUse the bottom bar to open the shop and room picker. Each room has its own furniture; purchases appear in their assigned places.\n\nTOY COLLECTION\nCAT toys live in the living room: up to 5 items and 1 bed at once. Remove stores an item; Add to room brings it back without buying it again.\n\nINTERACTION\nApproach an item's open entrance. Tapping distant furniture does not teleport the cat.");
            case 3:return T("KEDİ KOMUTLARI\nAlt şeritteki Kedi komutları düğmesini aç. Miyavla, Otur veya Patilerini topla seç. Patilerini toplamak, patilerin gövdenin altında durduğu rahat kedi pozudur.\n\nACELE YOK\nOturma ve patilerini toplayıp dinlenme sen Kalk diyene kadar sürer. Koltuk, minder ve salıncak da aynı şekilde çalışır. Kedinin yaptığı bakım veya hareket bitmeden yeni komut başlamaz.\n\nSESLER\nMiyavlama, mırlama, mama ve su seslerini Ayarlar içinden kapatabilirsin.","CAT COMMANDS\nOpen Cat commands on the bottom bar. Choose Meow, Sit or Loaf. A loaf is a relaxed pose with the paws tucked beneath the body.\n\nTAKE YOUR TIME\nSitting and loafing continue until you tap Get up. Sofas, cushions and swings work the same way. A new command waits for current care or movement to finish.\n\nSOUND\nYou can turn cat voices and care sounds off in Settings.");
            case 4:return T("KEDİ KOŞUSU\nSağa veya sola kaydırarak şerit değiştir. Yukarı kaydırarak zıpla, aşağı kaydırarak eğil. Jetonları topla; alçak ve yüksek engellerin açıklığına dikkat et.\n\nKEDİ YAKALAMA\nBir fareye dokun. Kedin ona döner, yaklaşır ve hazır olduğunda atılır. Temas ön patilerle gerçekleşir; her atılmadan sonra kısa bir toparlanma vardır.\n\nMOLA\nDuraklat düğmesi oyunu bekletir. Azaltılmış hareket seçeneği kamera ve süs hareketlerini sakinleştirir.","CAT RUNNER\nSwipe left or right to change lanes, up to jump and down to crouch. Collect coins and watch the clearance of low and high obstacles.\n\nCAT CATCH\nTap a mouse. Your cat turns, approaches and pounces when aligned. A catch requires front-paw contact; each pounce has a short recovery.\n\nTAKE A BREAK\nPause stops the game. Reduced motion calms camera and decorative movement.");
            default:return T("KAYIT\nİlerlemen otomatik kaydedilir. Yeni oyun mevcut ilerlemeyi sıfırlar; uyarıyı okuyup yalnız yeniden başlamak istiyorsan onayla.\n\nÖDÜLLER\nReklam ödülü isteğe bağlıdır. Bağlantı veya hizmet hazır değilse daha sonra tekrar deneyebilirsin.\n\nRAHAT OYNA\nUzun oyunlarda ara ver. Ses ve azaltılmış hareket ayarlarını kendine göre seç. Bu rehbere Kedi komutları içindeki Oyun rehberi sekmesinden istediğin zaman dönebilirsin.","SAVING\nProgress saves automatically. New game resets existing progress; read its warning and confirm only if you want to start again.\n\nREWARDS\nRewarded ads are optional. If the connection or service is unavailable, try again later.\n\nPLAY COMFORTABLY\nTake breaks during long sessions. Choose sound and reduced-motion settings that suit you. You can reopen this guide from the Play guide tab in Cat commands at any time.");}
    }
}
