using System.Collections.Generic;
using System.Globalization;

public static class GameProductCopy
{
    private static readonly Dictionary<string,string[]> Turkish=new Dictionary<string,string[]>
    {
        {"home.ball-basket",new[]{"Top sepeti","Yumuşak toplarla evde kovalamaca zamanı."}},
        {"home.scratch-post",new[]{"Tırmalama direği","Gerinen patiler için sağlam bir tırmalama alanı."}},
        {"cat.cozy-pod-bed",new[]{"Yumuşak kedi yatağı","Ailenin yanında kısa uykular için rahat bir yatak."}},
        {"cat.toy-mouse",new[]{"Oyuncak fare","Evde hareketli oyunlar için renkli bir fare."}},
        {"cat.play-tunnel",new[]{"Oyun tüneli","Girişinde oyuncağı olan renkli bir saklanma tüneli."}},
        {"cat.ceramic-bowl",new[]{"Seramik mama kabı","Yemek köşesine yakışan sağlam bir seramik kap."}},
        {"cat.cloud-bed",new[]{"Bulut yatak","Uzun öğle uykuları için yumuşacık bir yatak."}},
        {"cat.canopy-bed",new[]{"Tenteli kedi yatağı","İçine gir, minderi patile ve tentenin altında kıvrılıp uyu."}},
        {"cat.treat-jar",new[]{"Ödül bulmacası","Meraklı patilerle oynayan düğmesi ve hareketli kapağıyla küçük bir bulmaca."}},
        {"cat.feather-toy",new[]{"Yaylı tüy oyuncağı","Pati dokunuşuyla salınan renkli tüyler."}},
        {"cat.collar",new[]{"Döner top pisti","Topu patile, yuvarlak pistte dönmesini izle."}},
        {"cat.leash",new[]{"Kurdele oyun minderi","Yumuşak minder üzerinde kıpırdayan kurdeleyi yakala."}},
        {"cat.bell-collar",new[]{"Çıngıraklı teker","Pati dokunuşuyla dönen küçük bir çıngırak oyuncağı."}},
        {"cat.kibble-bag",new[]{"Mama bulmacası","Hareketli düğmesiyle meraklı patileri oyuna çağırır."}},
        {"cat.nap-pillow",new[]{"Uyku minderi","Güneşli bir köşede kısa bir mola için."}},
        {"cat.catnip-plant",new[]{"Kedi çimi","Meraklı patiler için küçük yeşil bir saksı."}},
        {"cat.cardboard-hideout",new[]{"Karton saklanma kutusu","Bazen en sevilen oyuncak basit bir kutudur."}},
        {"room.tv-console",new[]{"Modern televizyon","TV ünitesinin üzerine otomatik yerleşir. Önce TV ünitesi gerekir."}},
        {"room.tv-unit",new[]{"TV ünitesi","Televizyonu taşıyan geniş ve alçak bir ünite."}},
        {"room.game-console",new[]{"Oyun konsolu","Kumandasıyla birlikte salonun oyun köşesine yerleşir."}},
        {"room.floor-lamp",new[]{"Lambader","Okuma köşesine sıcak bir ışık katar."}},
        {"room.side-table",new[]{"Yan sehpa","Koltuk yanına yakışan küçük, yuvarlak sehpa."}},
        {"room.sofa",new[]{"İki kişilik kanepe","Salonun merkezinde rahat bir oturma alanı."}},
        {"room.armchair",new[]{"Rahat berjer","Okumak ve dinlenmek için sıcak bir köşe."}},
        {"room.coffee-table",new[]{"Orta sehpa","Salonun ortasına yakışan alçak ahşap sehpa."}},
        {"room.carpet",new[]{"Dokuma halı","Odaya renk ve sıcaklık katan bir halı."}},
        {"room.bookshelf",new[]{"Uzun kitaplık","Renkli kitap setinin yerleşeceği üç raflı kitaplık."}},
        {"room.colorful-book-set",new[]{"Renkli kitap seti","On kitap üç rafa sırayla dizilir. Önce kitaplık gerekir."}},
        {"room.tall-plant",new[]{"Büyük salon bitkisi","Salon köşesine canlı bir yeşil dokunuş."}},
        {"room.small-plant",new[]{"Masa bitkisi","Güneşli köşelere yakışan küçük bir saksı."}},
        {"room.modern-painting",new[]{"Modern tablo","Duvara renk katan çerçeveli bir eser."}},
        {"room.mirror",new[]{"Duvar aynası","Odayı aydınlık gösteren sade bir ayna."}},
        {"room.wall-clock",new[]{"Yuvarlak duvar saati","Salonun görünümünü tamamlayan bir saat."}},
        {"room.stereo",new[]{"Ses sistemi","Ana ünite ve iki uyumlu hoparlör."}},
        {"room.retro-tv",new[]{"Retro televizyon","Nostaljik bir oda için sevimli bir televizyon."}},
        {"room.stool",new[]{"Dekoratif tabure","Okuma köşesini tamamlayan küçük bir tabure."}},
        {"bathroom.bath-mat",new[]{"Patili banyo paspası","Yumuşak yüzeyinde patilerini dinlendirsin."}},
        {"bathroom.laundry-hamper",new[]{"Çamaşır sepeti","Meraklı kediler için renkli bir keşif köşesi."}},
        {"bathroom.litter-box",new[]{"Kedi tuvaleti","Bakım köşesine yerleşen alçak kenarlı kum kabı."}},
        {"bathroom.grooming-cart",new[]{"Bakım arabası","Fırçalar ve bakım malzemeleri tek bir yerde."}},
        {"bathroom.towel-storage",new[]{"Havlu rafı","Renkli havlularla dolu zarif bir raf."}},
        {"bathroom.wall-mirror",new[]{"Yuvarlak banyo aynası","Meraklı yansımalar için aydınlık bir ayna."}},
        {"bathroom.toilet",new[]{"Pastel klozet","Banyonun bakım alanını tamamlayan tasarım."}},
        {"bathroom.vanity-sink",new[]{"Lavabo dolabı","Parlak lavabo ve altında düzenli bir depolama alanı."}},
        {"bathroom.tub",new[]{"Patili küvet","Kedinin kenarını keşfedebileceği şık bir küvet."}},
        {"bathroom.shower",new[]{"Renkli duş","Cam bölmeli, renkli çerçeveli bir duş alanı."}},
        {"kitchen.paw-mat",new[]{"Patili mutfak halısı","Kahvaltı köşesinde yumuşak bir mola."}},
        {"kitchen.fruit-basket",new[]{"Meyve sepeti","Renkli meyvelerle dolu dekoratif sepet."}},
        {"kitchen.feeding-station",new[]{"İkili mama istasyonu","Kolay ulaşılan iki kapla düzenli bir beslenme köşesi."}},
        {"kitchen.counter-stool",new[]{"Mutfak taburesi","Kahvaltı köşesine yakışan rahat bir tabure."}},
        {"kitchen.pantry-shelf",new[]{"Kiler rafı","Renkli kavanozlarla dolu bir keşif alanı."}},
        {"kitchen.dish-cart",new[]{"Servis arabası","Bardak ve tabakları taşıyan küçük bir araba."}},
        {"kitchen.sink-cabinet",new[]{"Patili lavabo dolabı","Mercan ve krem renklerinde şık bir lavabo."}},
        {"kitchen.refrigerator",new[]{"Pastel buzdolabı","Patili mıknatıslarla süslü, ferah bir tasarım."}},
        {"kitchen.stove-oven",new[]{"Ocak ve fırın","Mutfak köşesini tamamlayan sıcak tonlar."}},
        {"kitchen.island",new[]{"Mutfak adası","Geniş yüzeyiyle mutfağın buluşma noktası."}},
        {"bedroom.paw-rug",new[]{"Yıldızlı pati halısı","Uykulu patiler için yumuşak bir halı."}},
        {"bedroom.night-light",new[]{"Ay gece lambası","Yatma saatine yumuşak bir ay ışığı."}},
        {"bedroom.dream-art",new[]{"Rüya tablosu","Yıldız ve bulutlarla sakin bir duvar süsü."}},
        {"bedroom.yarn-basket",new[]{"Yumak sepeti","Sessiz oyunlar için renkli yumaklar."}},
        {"bedroom.nightstand",new[]{"Pastel komodin","Minik pati kulpuyla sevimli bir komodin."}},
        {"bedroom.vanity-stool",new[]{"Bulut tabure","Yumuşak minderli yuvarlak bir tabure."}},
        {"bedroom.wardrobe",new[]{"Renkli gardırop","Pastel kapaklarla odaya neşe katan dolap."}},
        {"bedroom.window-daybed",new[]{"Pencere önü divanı","Güneşli uykular için minderli bir köşe."}},
        {"bedroom.star-canopy",new[]{"Yıldızlı uyku çadırı","Sallanan yıldızların altında saklı bir uyku alanı."}},
        {"bedroom.queen-bed",new[]{"Büyük bulut yatak","Rahat yastıklarla uzun uykulara hazır."}},
        {"garden.yarn-ball",new[]{"Bahçe yumağı","Çimlerde kovalamak için parlak renkli yumak."}},
        {"garden.flower-pots",new[]{"Çiçek saksıları","Bahçeye renk katan küçük çiçekler."}},
        {"garden.daisy-bed",new[]{"Papatya köşesi","Bahçe kenarında neşeli bir papatya alanı."}},
        {"garden.sapling",new[]{"Küçük bahçe ağacı","Meraklı kediler için gölgeli bir köşe."}},
        {"garden.bird-bath",new[]{"Kuş banyosu","Küçük kuşların ziyaret ettiği sığ bir havuz."}},
        {"garden.sun-lounger",new[]{"Şezlong","Güneşli molalar için rahat bir uzanma alanı."}},
        {"garden.bistro-set",new[]{"Bahçe masa takımı","Açık havada küçük bir buluşma köşesi."}},
        {"garden.grill",new[]{"Patili mangal","Bahçe düzenini tamamlayan renkli bir mangal."}},
        {"garden.hammock",new[]{"Bahçe hamağı","Uzun uykular için hafifçe sallanan hamak."}},
        {"garden.pergola",new[]{"Güneş pergolası","Bahçeyi çerçeveleyen ferah bir gölgelik."}},
        {"balcony.sun-mat",new[]{"Güneş minderi","Balkon zemininde sıcak bir güneş molası."}},
        {"balcony.planter-box",new[]{"Çiçek kasası","Renkli çiçeklerle dolu ahşap bir kasa."}},
        {"balcony.herb-shelf",new[]{"Bitki rafı","Güneşli köşede küçük saksılarla dolu raf."}},
        {"balcony.railing-flowers",new[]{"Korkuluk çiçekleri","Şehir manzarasına uzanan renkli çiçekler."}},
        {"balcony.bird-feeder",new[]{"Kuş yemliği","Küçük kuşları balkona davet eden yemlik."}},
        {"balcony.lantern-string",new[]{"Fener dizisi","Akşama sıcak ışık katan fenerler."}},
        {"balcony.cushion-bench",new[]{"Minderli bank","Rahat minderlerle dolu alçak bir bank."}},
        {"balcony.side-table",new[]{"Balkon sehpası","Güneşli köşeye yakışan küçük yuvarlak sehpa."}},
        {"balcony.hanging-chair",new[]{"Asma koltuk","Hafifçe sallanan, yumurta biçimli koltuk."}},
        {"balcony.sun-awning",new[]{"Güneş tentesi","Balkona gölge sağlayan çizgili tente."}},
        {"patio.stone-rug",new[]{"Avlu halısı","Taş zemine sıcaklık katan dış mekân halısı."}},
        {"patio.potted-ferns",new[]{"Eğrelti saksıları","Taş saksılarda canlı yeşil yapraklar."}},
        {"patio.herb-trough",new[]{"Uzun bitki saksısı","Avlu kenarına uzanan yeşil bir köşe."}},
        {"patio.string-lights",new[]{"Avlu ışıkları","Kendi direkleri üzerinde sıcak akşam ışıkları."}},
        {"patio.water-fountain",new[]{"Su fıskiyesi","Katlarından su süzülen küçük taş fıskiye."}},
        {"patio.fire-pit",new[]{"Ateş çanağı","Avluya sıcak bir parıltı katan taş çanak."}},
        {"patio.dining-set",new[]{"Avlu yemek takımı","Açık havada yemek için masa ve dört sandalye."}},
        {"patio.parasol",new[]{"Bahçe şemsiyesi","Dinlenme alanına serin gölge sağlar."}},
        {"patio.porch-swing",new[]{"Avlu salıncağı","Sağlam çerçevesinde sallanan minderli bank."}},
        {"patio.pergola-arch",new[]{"Sarmaşıklı kemer","Avlunun üzerinde yükselen zarif bir kemer."}},
        {"loft.floor-runner",new[]{"Üst kat yolluğu","Ahşap zemine sıcaklık katan dokuma yolluk."}},
        {"loft.floor-cushions",new[]{"Yer minderleri","Uzanmak için üst üste yumuşak minderler."}},
        {"loft.book-stack",new[]{"Kitap yığınları","Okuma köşesinde renkli kitaplar."}},
        {"loft.arc-lamp",new[]{"Kavisli lambader","Dinlenme köşesine uzanan sıcak bir ışık."}},
        {"loft.bean-bag",new[]{"Armut koltuk","Uykucu kedinin şekline uyum sağlayan koltuk."}},
        {"loft.record-player",new[]{"Plak çalar","Sakin öğleden sonraları için retro bir köşe."}},
        {"loft.study-desk",new[]{"Çalışma masası","Lambası ve sandalyesiyle düzenli bir masa."}},
        {"loft.wall-gallery",new[]{"Duvar galerisi","Küçük, renkli çerçevelerden bir sanat köşesi."}},
        {"loft.tall-bookcase",new[]{"Büyük kitaplık","Kitaplar ve bitkilerle dolu yüksek bir raf."}},
        {"loft.chaise-lounge",new[]{"Dinlenme koltuğu","Pencere yanında güneşli uykular için."}},
        {"home.rooms-preview",new[]{"Salon","Evinin ilk odası. On parçalık koleksiyon seni bekliyor."}},
        {"home.bathroom-preview",new[]{"Banyo","Bakım ve keşif için on parçalık yeni bir koleksiyon."}},
        {"home.kitchen-preview",new[]{"Mutfak","Beslenme ve meraklı patiler için on yeni eşya."}},
        {"home.bedroom-preview",new[]{"Yatak odası","Sakin uykular için on parçalık bir koleksiyon."}},
        {"home.garden-preview",new[]{"Bahçe","Çimler, kuşlar ve on bahçe eşyasıyla açık hava keyfi."}},
        {"home.balcony-preview",new[]{"Balkon","Şehir manzarası ve on parçalık güneşli bir koleksiyon."}},
        {"home.patio-preview",new[]{"Avlu","Fıskiye ve salıncakla on parçalık dış mekân koleksiyonu."}},
        {"home.second-floor-preview",new[]{"Üst kat","Büyük pencerenin yanında on parçalık rahat bir koleksiyon."}}
    };
    public static string Title(string id,string fallback)
    {
        if(GameLanguageService.Current==GameLanguage.Turkish && Turkish.TryGetValue(id,out var copy))return copy[0];
        return CultureInfo.InvariantCulture.TextInfo.ToTitleCase((fallback??string.Empty).ToLowerInvariant()).Replace("Tv ","TV ");
    }
    public static string Description(string id,string fallback)
    {
        if(GameLanguageService.Current==GameLanguage.Turkish && Turkish.TryGetValue(id,out var copy))return copy[1];
        if(id=="room.colorful-book-set")return "Ten books fill three shelves automatically. Requires the tall bookshelf.";
        if(id=="patio.string-lights")return "Warm evening lights on their own two posts.";
        if(id=="bathroom.tub")return "A premium bathtub with an edge your cat can explore.";
        return fallback;
    }
}
