using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

public enum GameLanguage
{
    English = 0,
    Turkish = 1
}

/// <summary>
/// Small, package-free localization seam for Cat Home. The selected language
/// lives outside the gameplay save so NEW GAME never changes it.
/// </summary>
public static class GameLanguageService
{
    public const string PlayerPrefsKey = "cat-home.language";

    private static readonly Dictionary<string, string> English = new()
    {
        ["care.not_hungry"] = "I’m not hungry right now.",
        ["care.not_thirsty"] = "I’m not thirsty right now.",
        ["care.unavailable"] = "Care is unavailable right now.",
        ["interaction.action_fallback"] = "Interact",
        ["interaction.status_fallback"] = "Exploring",
        ["interaction.feedback_fallback"] = "Let’s try again in a moment.",
        ["interaction.unavailable"] = "I can’t use this right now.",
        ["interaction.store_required"] = "Available in the shop.",
        ["interaction.bond_required"] = "Requires {0} bond XP.",
        ["interaction.nothing_reach"] = "There’s nothing to reach.",
        ["interaction.nothing_push"] = "There’s nothing to push.",
        ["interaction.no_paper"] = "There’s no paper to play with.",
        ["interaction.no_room_above"] = "There’s not enough room up there.",
        ["interaction.make_room"] = "I need a little more space here.",
        ["interaction.fern.action"] = "Inspect the planters",
        ["interaction.fern.progress"] = "Watching the leaves",
        ["interaction.fern.complete"] = "The leaves are lovely to watch.",
        ["shop.future_content"] = "New content is coming soon.",
        ["shop.level_label"] = "Level {0}",
        ["shop.level_required"] = "Reach home level {0} to unlock this item.",
        ["shop.collection_required"] = "Add {0} more items to {1} to unlock {2}.",
        ["shop.coins_short"] = "You need {0} more coins. Play Cat Runner or use diamonds.",
        ["shop.diamonds_short"] = "You need {0} more diamonds.",
        ["shop.buy_first"] = "Get {0} first",
        ["shop.place_first"] = "Place {0} first.",
        ["shop.books_found"] = "Bookshelf found · Confirm to arrange the books",
        ["shop.drag_books"] = "Drag the books onto your bookshelf",
        ["shop.surface_found"] = "{0} found · Rotate or confirm",
        ["shop.drag_surface"] = "Drag this item onto {0}",
        ["localization.unavailable"] = "Unavailable right now.",
        ["interaction.watching"] = "Watching",
        ["product.unknown"] = "Item",
        ["product.description_unknown"] = "This item’s description is not ready yet.",
        ["rooms.unavailable"] = "This room is not available yet.",
        ["rooms.unlock_room_hint"] = "Unlock {0} in Shop > Home.",
        ["rooms.already_here"] = "You are already in {0}.",
        ["rooms.open_failed"] = "The room could not be opened. Try again.",
        ["rooms.travelling"] = "Opening {0}…",
        ["rooms.arrived"] = "{0} is ready!",
        ["edit.room"] = "Edit {0}",
        ["edit.select_item"] = "Select an item",
        ["edit.tap_select"] = "Tap to select",
        ["edit.buy_hint"] = "Get room items in the shop to decorate",
        ["edit.move_hint"] = "Tap an item to move it",
        ["edit.store"] = "Put away",
        ["edit.wall"] = "Wall area",
        ["edit.bookshelf"] = "On the bookshelf",
        ["edit.surface"] = "Only on {0}",
        ["edit.floor"] = "Floor area",
        ["edit.drag_wall"] = "Drag along the lilac wall area",
        ["edit.drag_surface"] = "Drag onto the gold target",
        ["edit.drag_floor"] = "Drag inside the mint floor area",
        ["edit.only_surface"] = "This item only fits the gold target",
        ["edit.blocked"] = "Blocked · Move away from other furniture",
        ["edit.restore_required"] = "Put {0} back in the room first",
        ["edit.unavailable"] = "This item cannot be moved right now.",
        ["record.on"] = "Music time!",
        ["record.off"] = "A little quiet.",
        ["record.not_ready"] = "The record is not ready yet.",
        ["record.action"] = "Tap the record",
        ["idle.hungry"] = "I’m hungry…",
        ["idle.thirsty"] = "I need a drink…",
        ["idle.tired"] = "I need a nap…",
        ["idle.sleepy"] = "Sleepy…",
        ["idle.bored"] = "I’m bored…",
        ["idle.pet"] = "{0} wants a pet!",
        ["edit.returned_safe"] = "Blocked · Returned to the last safe spot",
        ["edit.placed_adjust"] = "Placed · Drag again to adjust",
        ["edit.from_storage"] = "From storage · Drag it into place",
        ["edit.no_turn_room"] = "Not enough room to turn here",
        ["edit.turned_saved"] = "Turned and saved",
        ["edit.save_failed"] = "Could not save this placement",
        ["edit.saved"] = "Placement saved",
        ["edit.choose_to_store"] = "Choose an item to put away",
        ["edit.cannot_store"] = "This item cannot be put away",
        ["edit.stored_attached"] = "Put away with its attached item",
        ["edit.stored_restore"] = "Put away · Use the title arrows to bring it back",
        ["shop.collection_ready"] = "Collection complete",
        ["shop.next_free"] = "Next: {0} · Free test",
        ["shop.next_ready"] = "Next: {0} · Ready to buy",
        ["shop.next_coins"] = "Next: {0} · Need {1} coins",
        ["tutorial.pet_action"] = "Swipe to pet",
        ["tutorial.move_action"] = "Move to continue",
        ["tutorial.watch_needs"] = "Watch my needs",
        ["tutorial.food_water"] = "Food and water",
        ["tutorial.rest_bed"] = "Rest in bed",
        ["companion.loaf_action"] = "Loaf",
        ["companion.loaf_progress"] = "Loaf time",
        ["ranks.daily"] = "Daily",
        ["ranks.weekly"] = "Weekly",
        ["ranks.all"] = "All time",
        ["ranks.refresh"] = "Refresh",
        ["ranks.privacy"] = "Only your cat’s name appears. Your email stays private.",
        ["ranks.rewards"] = "Daily and weekly prizes are added after results are verified.",
        ["catch.hint"] = "Tap a mouse · Your cat chases and pounces",
        ["games.time"] = "Time left",
        ["catch.mice"] = "Mice · Coins",

        ["games.title"] = "A little adventure",
        ["games.intro"] = "Two ways to play with your cat. Each has its own lives and records.",
        ["games.rankings"] = "Leaderboards",
        ["runner.card_intro"] = "An endless dash through a playful pet town.",
        ["catch.card_intro"] = "A quick sixty-second mouse hunt.",
        ["games.life_count"] = "{0} / {1} lives ready",
        ["runner.intro"] = "Follow the paw coins. Leap over toys and find a new personal best.",
        ["catch.intro"] = "Sixty seconds, quick paws and playful little mice.",
        ["catch.rules"] = "Tap a mouse; your cat chases and catches it. Chain catches for a combo.",
        ["runner.start"] = "Start run",
        ["catch.start"] = "Start hunt",
        ["runner.controls"] = "Drag sideways · swipe up to jump · swipe down to slide",
        ["catch.controls"] = "Tap to move · tap a mouse to chase",
        ["games.rewarded"] = "Watch for 2 lives",
        ["games.home"] = "Back home",
        ["games.new_best"] = "New best!",
        ["games.score"] = "Your score",
        ["games.earned"] = "Coins earned",
        ["games.paused"] = "Take a little break",
        ["games.resume"] = "Keep playing",
        ["games.skip"] = "Skip",
        ["runner.again"] = "Run again",
        ["catch.again"] = "Hunt again",
        ["games.best"] = "Best score · {0}",
        ["games.unlimited"] = "Unlimited lives",
        ["games.lives_ready"] = "{0} / {1} lives ready · one per game",
        ["games.next_life"] = "Next life in {0}",
        ["runner.complete"] = "A lovely run!",
        ["games.reward_retry"] = "Let’s finish saving your reward",
        ["games.no_lives"] = "Time for a little rest",
        ["runner.again_lives"] = "Run again · {0} lives",
        ["runner.result_stats"] = "Time {0} · Distance {1} m\nBest combo ×{2} · Hits {3}\nBest score {4} · Happiness bonus +{5}",
        ["catch.complete"] = "Quick paws, great hunt!",
        ["catch.nice_try"] = "Every hunt is practice",
        ["catch.result_stats"] = "{0} mice caught\nPersonal best · {1}",
        ["celebration.level"] = "Your home is growing!",
        ["celebration.level_body"] = "You reached home level {0}.",
        ["celebration.coins"] = "+{0} coins",
        ["celebration.double"] = "Watch & double",
        ["celebration.collection"] = "A lovely collection, complete!",
        ["celebration.care"] = "A wonderful first day",
        ["celebration.care_reward"] = "+180 coins · Cat Runner is ready",
        ["celebration.play"] = "Let’s play",
        ["quests.title"] = "A happy home, one step at a time",
        ["quests.chapter_tab"] = "Home journey",
        ["quests.daily_tab"] = "Today",
        ["quests.refresh_daily"] = "Fresh goals every day",
        ["quests.chapter"] = "Chapter {0}",
        ["quests.claim"] = "Collect",
        ["quests.claimed"] = "Collected",
        ["quests.locked"] = "Not yet",
        ["quests.active"] = "In progress",
        ["quests.unavailable"] = "Your next goals will appear here.",
        ["quests.wallet"] = "{0} coins   ·   {1} bond XP   ·   {2} diamonds",
        ["currency.coins"] = "coins",
        ["currency.bond"] = "bond XP",
        ["return.title"] = "Welcome back!",
        ["return.continue"] = "Back to my cat",
        ["return.away"] = "You were away for {0}.",
        ["return.water"] = "A little fresh water would make your cat happy.",
        ["return.food"] = "Your cat is ready for a tasty meal.",
        ["return.rest"] = "A cosy nap will help your cat recharge.",
        ["return.nap"] = "A cosy nap restored {0}% energy.",
        ["return.missed"] = "Your cat missed you. Let’s spend some time together.",
        ["shop.required"] = "First: {0}",
        ["shop.required_body"] = "{0} needs {1}. This purchase adds the required item first.",
        ["shop.requested"] = "Then you can add {0}.",
        ["shop.room_purchase"] = "A new room for you and your cat.",
        ["shop.cat_placement"] = "Choose a place for this cat essential after purchase.",
        ["shop.confirm"] = "Confirm purchase",
        ["shop.confirm_body"] = "Buy {0} for {1} diamonds?",
        ["shop.furniture_title"] = "{0} collection",
        ["diamonds.title"] = "A little extra sparkle",
        ["diamonds.subtitle"] = "Choose the right diamond pack for your home.",
        ["diamonds.units"] = "diamonds",
        ["diamonds.unavailable"] = "Unavailable",
        ["diamonds.recommended"] = "Just enough",
        ["diamonds.store_unavailable"] = "Purchases are unavailable right now. Please try again later.",
        ["diamonds.choose"] = "Choose a pack. Your device store confirms the price and payment.",
        ["diamonds.complete"] = "Your diamonds are ready!",
        ["diamonds.failed"] = "Purchase could not be completed. Please try again.",
        ["diamonds.connecting"] = "Waiting for your device store…",
        ["diamonds.loading"] = "Loading price…",
        ["diamonds.cancelled"] = "Purchase cancelled. No diamonds were added.",
        ["common.cancel"] = "Cancel",
        ["privacy.confirm.title"] = "Delete your cloud account?",
        ["privacy.confirm.body"] = "This permanently deletes your cloud save and Cat Home sign-in account. You cannot undo it. Your local progress stays on this device.",
        ["privacy.confirm.action"] = "Delete cloud account",
        ["settings.group.sound"] = "Sound",
        ["settings.group.access"] = "Accessibility & language",
        ["settings.connected"] = "Connected",
        ["settings.connect"] = "Connect Google",
        ["cat.title"] = "My cat",
        ["mycat.title"] = "My cat",
        ["cat.subtitle"] = "Your companion, your way.",
        ["cat.appearance"] = "Appearance",
        ["cat.name"] = "Your cat's name",
        ["cat.coat"] = "Coat colour",
        ["cat.continue"] = "CONTINUE WITH THIS CAT",
        ["cat.current"] = "Your current companion",
        ["cat.preview"] = "Preview · save with Continue",
        ["rooms.title"] = "Your home",
        ["rooms.subtitle"] = "Eight lovely rooms.\nOne happy cat.",
        ["rooms.hint"] = "Complete each collection to discover the next room.",
        ["rooms.locked"] = "Locked",
        ["rooms.current"] = "Here now",
        ["rooms.ready"] = "Ready to visit",
        ["rooms.unlock_hint"] = "Unlock in the shop",
        ["rooms.unlock"] = "View",
        ["rooms.visit"] = "Visit",
        ["rooms.progress"] = "{0} / {1} items at home",
        ["rooms.current_hint"] = "Your cat is in {0}.",
        ["home.hunger"] = "Hunger",
        ["home.thirst"] = "Water",
        ["home.energy"] = "Energy",
        ["home.level"] = "Level {0}",
        ["cloud.status.ready"] = "Google is connected. Sync to check your cloud save.",
        ["shop.title"] = "Shop",
        ["shop.subtitle"] = "Little things that make a home.",
        ["shop.cat"] = "Cat essentials",
        ["shop.room"] = "Furniture",
        ["shop.home"] = "Rooms",
        ["shop.placement"] = "Added to its designed place at home.",
        ["shop.owned"] = "At home",
        ["shop.in_collection"] = "In collection",
        ["shop.in_room"] = "In room",
        ["shop.place"] = "Place here",
        ["shop.cancel_placement"] = "Cancel",
        ["shop.progress"] = "{0} / {1} collected",
        ["shop.buy_coins"] = "Buy for {0} coins",
        ["shop.buy_diamonds"] = "Buy for {0} diamonds",
        ["shop.need_coins"] = "{0} more coins needed",
        ["common.not_now"] = "Not now",
        ["title.greeting.empty"] = "Your cat is waiting",
        ["title.greeting.named"] = "{0} is waiting for you",
        ["title.home.empty"] = "Welcome\nhome.",
        ["title.home.named"] = "Welcome\nhome.",
        ["title.play"] = "PLAY",
        ["title.continue"] = "Continue",
        ["title.home_level"] = "Home level {0}",
        ["title.collection"] = "{0} OF {1} • COLLECTED",
        ["title.settings"] = "Settings",
        ["title.credits"] = "Credits",
        ["title.quit"] = "Quit",
        ["title.new_game"] = "New game",
        ["title.promise"] = "Another lovely day together.",
        ["title.shortcuts"] = "CHOOSE YOUR HAPPY PLACE",
        ["title.shop"] = "Shop",
        ["title.my_cat"] = "My cat",
        ["title.rooms"] = "Rooms",
        ["title.games"] = "Games",
        ["title.after_tour"] = "AFTER TOUR",
        ["credits.title"] = "Made with care",
        ["credits.body"] = "Cat models & animations · Polyperfect\nGame engine · Unity\nInterface typeface · Fredoka\n\nThank you for making a home for your cat.",
        ["common.close"] = "Close",
        ["common.back"] = "BACK",
        ["menu.quests"] = "Goals",
        ["menu.main_menu"] = "Main menu",
        ["settings.badge"] = "GEAR",
        ["settings.title"] = "Settings",
        ["settings.subtitle"] = "Make yourself comfortable.",
        ["settings.row.music"] = "Home music",
        ["settings.row.sound"] = "Home sound effects",
        ["settings.row.game_sound"] = "Mini-game sound",
        ["settings.row.haptics"] = "Vibration",
        ["settings.row.reduced_motion"] = "Reduced motion",
        ["settings.row.language"] = "Language",
        ["settings.row.account"] = "Your account",
        ["settings.privacy_data"] = "PRIVACY & DATA",
        ["settings.on"] = "ON",
        ["settings.off"] = "OFF",
        ["language.english"] = "ENGLISH",
        ["language.turkish"] = "TÜRKÇE",
        ["new_game.title"] = "Reset your progress?",
        ["new_game.body"] = "COINS, ROOMS, ITEMS, LEVELS AND SCORES WILL RESET.\nDIAMONDS, PURCHASE RIGHTS AND SETTINGS WILL STAY.",
        ["new_game.cancel"] = "CANCEL",
        ["new_game.confirm"] = "Reset progress",
        ["new_game.failed"] = "COULD NOT START A NEW GAME. YOUR CURRENT SAVE IS SAFE.",
        ["account.choice.title"] = "Keep your home safe",
        ["account.choice.subtitle"] = "Connect Google to protect your progress across devices.",
        ["account.google.action"] = "SIGN IN WITH GOOGLE",
        ["account.google.benefit"] = "CLOUD SAVE • ONLINE LEADERBOARDS • PLAY ON ANOTHER DEVICE",
        ["account.google.success"] = "GOOGLE ACCOUNT CONNECTED.",
        ["account.google.cancelled"] = "SIGN-IN WAS CANCELLED. YOUR CURRENT SAVE IS SAFE.",
        ["account.google.unavailable"] = "GOOGLE SIGN-IN IS NOT READY. CHECK THE CONNECTION OR ACCOUNT SETUP.",
        ["account.google.already_linked"] = "THIS ACCOUNT ALREADY HAS A CAT HOME. THE NEWEST SAVE WILL LOAD AUTOMATICALLY.",
        ["account.guest.action"] = "CONTINUE AS A GUEST",
        ["account.guest.note"] = "Guest progress is saved on this device.",
        ["account.status.none"] = "CHOOSE",
        ["account.status.guest"] = "GUEST",
        ["account.status.guest_offline"] = "GUEST • OFFLINE",
        ["account.status.google"] = "GOOGLE CONNECTED",
        ["account.status.connecting"] = "CONNECTING...",
        ["privacy.title"] = "Privacy & your data",
        ["privacy.policy"] = "PRIVACY POLICY",
        ["privacy.delete_info"] = "ACCOUNT DELETION INFO",
        ["privacy.data_requests"] = "DATA REQUESTS",
        ["privacy.sync_now"] = "SYNC NOW",
        ["privacy.delete_cloud"] = "DELETE CLOUD ACCOUNT & DATA",
        ["privacy.delete_confirm"] = "TAP AGAIN TO DELETE",
        ["privacy.delete_note"] = "YOUR LOCAL GUEST SAVE STAYS ON THIS DEVICE. CLOUD DATA AND YOUR PLAYER ACCOUNT WILL BE PERMANENTLY DELETED.",
        ["privacy.unity_portal"] = "UNITY PLAYER ACCOUNT PORTAL",
        ["privacy.guest_status"] = "SIGN IN WITH GOOGLE TO USE CLOUD SAVE AND ACCOUNT DELETION.",
        ["cloud.status.offline"] = "GOOGLE SIGN-IN IS REQUIRED FOR CLOUD SAVE.",
        ["cloud.status.syncing"] = "SYNCING DEVICE AND CLOUD SAVE...",
        ["cloud.status.empty"] = "NO LOCAL SAVE IS READY TO SYNC.",
        ["cloud.status.synced"] = "DEVICE AND CLOUD SAVE ARE UP TO DATE.",
        ["cloud.status.invalid"] = "THE CLOUD SAVE COULD NOT BE READ. YOUR DEVICE SAVE IS SAFE.",
        ["cloud.status.unavailable"] = "CLOUD SAVE IS TEMPORARILY UNAVAILABLE. YOUR DEVICE SAVE IS SAFE.",
        ["cloud.status.cloud_applied"] = "CLOUD SAVE LOADED ON THIS DEVICE.",
        ["cloud.status.deleting"] = "DELETING CLOUD DATA AND PLAYER ACCOUNT...",
        ["cloud.status.deleted"] = "CLOUD DATA AND PLAYER ACCOUNT DELETED. CONTINUING AS A GUEST.",
        ["cloud.status.delete_failed"] = "DELETION COULD NOT FINISH. NOTHING ELSE WAS CHANGED."
    };

    private static readonly Dictionary<string, string> Turkish = new()
    {
        ["care.not_hungry"] = "Şu an aç değilim.",
        ["care.not_thirsty"] = "Şu an susamadım.",
        ["care.unavailable"] = "Şu anda bakım yapamıyorum.",
        ["interaction.action_fallback"] = "Etkileşime gir",
        ["interaction.status_fallback"] = "İlgileniyor",
        ["interaction.feedback_fallback"] = "Biraz sonra yeniden deneyelim.",
        ["interaction.unavailable"] = "Şu anda kullanamıyorum.",
        ["interaction.store_required"] = "Mağazadan edinmelisin.",
        ["interaction.bond_required"] = "{0} bağ puanı gerekli.",
        ["interaction.nothing_reach"] = "Uzanabileceğim bir şey yok.",
        ["interaction.nothing_push"] = "İtecek bir şey yok.",
        ["interaction.no_paper"] = "Oynayacak kâğıt yok.",
        ["interaction.no_room_above"] = "Yukarıda yeterli yer yok.",
        ["interaction.make_room"] = "Burada biraz daha boşluk gerekli.",
        ["interaction.fern.action"] = "Saksıları incele",
        ["interaction.fern.progress"] = "Yaprakları inceliyor",
        ["interaction.fern.complete"] = "Yaprakları seyretmek ne güzel.",
        ["shop.future_content"] = "Yeni içerikler yakında.",
        ["shop.level_label"] = "Seviye {0}",
        ["shop.level_required"] = "Bu eşya için ev seviyesi {0} gerekli.",
        ["shop.collection_required"] = "{2} için {1} koleksiyonuna {0} eşya daha ekle.",
        ["shop.coins_short"] = "{0} jeton daha gerekli. Kedi Koşusu oyna veya elmas kullan.",
        ["shop.diamonds_short"] = "{0} elmas daha gerekli.",
        ["shop.buy_first"] = "Önce {0} edin",
        ["shop.place_first"] = "Önce {0} yerleştir.",
        ["shop.books_found"] = "Kitaplık bulundu · Kitapları yerleştirmek için onayla",
        ["shop.drag_books"] = "Kitapları kitaplığın üzerine sürükle",
        ["shop.surface_found"] = "{0} bulundu · Döndür veya onayla",
        ["shop.drag_surface"] = "Eşyayı {0} üzerine sürükle",
        ["localization.unavailable"] = "Şu anda kullanılamıyor.",
        ["interaction.watching"] = "Seyrediyor",
        ["product.unknown"] = "Eşya",
        ["product.description_unknown"] = "Bu eşyanın açıklaması henüz hazır değil.",
        ["rooms.unavailable"] = "Bu oda henüz kullanılamıyor.",
        ["rooms.unlock_room_hint"] = "{0} için Mağaza > Ev bölümüne git.",
        ["rooms.already_here"] = "Zaten bu odadasın: {0}.",
        ["rooms.open_failed"] = "Oda açılamadı. Yeniden dene.",
        ["rooms.travelling"] = "{0} açılıyor…",
        ["rooms.arrived"] = "{0} hazır!",
        ["edit.room"] = "{0} düzeni",
        ["edit.select_item"] = "Bir eşya seç",
        ["edit.tap_select"] = "Seçmek için dokun",
        ["edit.buy_hint"] = "Evi süslemek için mağazadan eşya edin",
        ["edit.move_hint"] = "Taşımak istediğin eşyaya dokun",
        ["edit.store"] = "Kaldır",
        ["edit.wall"] = "Duvar alanı",
        ["edit.bookshelf"] = "Kitaplığın üzerine",
        ["edit.surface"] = "Yalnızca {0} üzerine",
        ["edit.floor"] = "Zemin alanı",
        ["edit.drag_wall"] = "Mor duvar alanında sürükle",
        ["edit.drag_surface"] = "Sarı hedef alanına sürükle",
        ["edit.drag_floor"] = "Yeşil zemin alanında sürükle",
        ["edit.only_surface"] = "Bu eşya yalnızca sarı hedefe yerleşir",
        ["edit.blocked"] = "Yer uygun değil · Diğer eşyalardan uzaklaştır",
        ["edit.restore_required"] = "Önce {0} eşyasını odaya geri yerleştir",
        ["edit.unavailable"] = "Bu eşya şu anda taşınamıyor.",
        ["record.on"] = "Müzik zamanı!",
        ["record.off"] = "Biraz sessizlik.",
        ["record.not_ready"] = "Plak henüz hazır değil.",
        ["record.action"] = "Pati at",
        ["idle.hungry"] = "Karnım acıktı…",
        ["idle.thirsty"] = "Biraz su içsem…",
        ["idle.tired"] = "Biraz dinlenmeliyim…",
        ["idle.sleepy"] = "Uykum geldi…",
        ["idle.bored"] = "Canım sıkıldı…",
        ["idle.pet"] = "{0} biraz ilgi istiyor!",
        ["edit.returned_safe"] = "Yer uygun değil · Önceki güvenli yere döndü",
        ["edit.placed_adjust"] = "Yerleştirildi · Düzenlemek için yeniden sürükle",
        ["edit.from_storage"] = "Koleksiyondan çıkarıldı · Yerine sürükle",
        ["edit.no_turn_room"] = "Burada döndürmek için yeterli yer yok",
        ["edit.turned_saved"] = "Döndürüldü ve kaydedildi",
        ["edit.save_failed"] = "Bu yerleşim kaydedilemedi",
        ["edit.saved"] = "Yerleşim kaydedildi",
        ["edit.choose_to_store"] = "Kaldırmak için bir eşya seç",
        ["edit.cannot_store"] = "Bu eşya kaldırılamıyor",
        ["edit.stored_attached"] = "Üzerindeki eşya ile birlikte kaldırıldı",
        ["edit.stored_restore"] = "Kaldırıldı · Geri getirmek için başlığın oklarını kullan",
        ["shop.collection_ready"] = "Koleksiyon tamamlandı",
        ["shop.next_free"] = "Sıradaki: {0} · Ücretsiz deneme",
        ["shop.next_ready"] = "Sıradaki: {0} · Satın alınabilir",
        ["shop.next_coins"] = "Sıradaki: {0} · {1} jeton gerekli",
        ["tutorial.pet_action"] = "Sevmek için okşa",
        ["tutorial.move_action"] = "Devam etmek için hareket et",
        ["tutorial.watch_needs"] = "İhtiyaçlarıma göz kulak ol",
        ["tutorial.food_water"] = "Mama ve su",
        ["tutorial.rest_bed"] = "Yatakta dinlen",
        ["companion.loaf_action"] = "Patilerini topla",
        ["companion.loaf_progress"] = "Patilerini toplayıp dinleniyor",
        ["ranks.daily"] = "Günlük",
        ["ranks.weekly"] = "Haftalık",
        ["ranks.all"] = "Tüm zamanlar",
        ["ranks.refresh"] = "Yenile",
        ["ranks.privacy"] = "Yalnızca kedinin adı görünür. E-posta adresin gizli kalır.",
        ["ranks.rewards"] = "Günlük ve haftalık ödüller doğrulanan sonuçlarla eklenir.",
        ["catch.hint"] = "Bir fareye dokun · Kedin kovalayıp yakalasın",
        ["games.time"] = "Kalan süre",
        ["catch.mice"] = "Fare · Jeton",

        ["games.title"] = "Küçük bir macera",
        ["games.intro"] = "Kedinle oynamanın iki yolu. Her oyunun canları ve rekorları ayrı.",
        ["games.rankings"] = "Liderlik tablosu",
        ["runner.card_intro"] = "Neşeli bir kedi kasabasında sonsuz koşu.",
        ["catch.card_intro"] = "Altmış saniyelik hızlı bir fare avı.",
        ["games.life_count"] = "{0} / {1} can hazır",
        ["runner.intro"] = "Pati jetonlarını takip et. Oyuncakların üzerinden atla, kendi rekorunu kır.",
        ["catch.intro"] = "Altmış saniye, hızlı patiler ve oyuncu küçük fareler.",
        ["catch.rules"] = "Fareye dokun; kedin takip edip yakalasın. Seri yakala, kombo yap.",
        ["runner.start"] = "Koşuya başla",
        ["catch.start"] = "Ava başla",
        ["runner.controls"] = "Yana sürükle · yukarı kaydır ve zıpla · aşağı kaydır ve eğil",
        ["catch.controls"] = "Hareket için dokun · kovalamak için fareye dokun",
        ["games.rewarded"] = "İzle, 2 can kazan",
        ["games.home"] = "Eve dön",
        ["games.new_best"] = "Yeni rekor!",
        ["games.score"] = "Skorun",
        ["games.earned"] = "Kazanılan jeton",
        ["games.paused"] = "Küçük bir mola",
        ["games.resume"] = "Oyuna devam et",
        ["games.skip"] = "Atla",
        ["runner.again"] = "Yeniden koş",
        ["catch.again"] = "Yeniden avlan",
        ["games.best"] = "En iyi skor · {0}",
        ["games.unlimited"] = "Sınırsız can",
        ["games.lives_ready"] = "{0} / {1} can hazır · oyun başına bir can",
        ["games.next_life"] = "Sonraki can: {0}",
        ["runner.complete"] = "Güzel bir koşuydu!",
        ["games.reward_retry"] = "Ödül kaydını tamamlayalım",
        ["games.no_lives"] = "Biraz dinlenme zamanı",
        ["runner.again_lives"] = "Yeniden koş · {0} can",
        ["runner.result_stats"] = "Süre {0} · Mesafe {1} m\nEn iyi kombo ×{2} · Çarpma {3}\nEn iyi skor {4} · Mutluluk bonusu +{5}",
        ["catch.complete"] = "Hızlı patiler, harika av!",
        ["catch.nice_try"] = "Her av yeni bir deneyim",
        ["catch.result_stats"] = "{0} fare yakalandı\nKişisel rekor · {1}",
        ["celebration.level"] = "Yuvan büyüyor!",
        ["celebration.level_body"] = "Yuva seviyen {0} oldu.",
        ["celebration.coins"] = "+{0} jeton",
        ["celebration.double"] = "İzle ve ikiye katla",
        ["celebration.collection"] = "Güzel bir koleksiyon tamamlandı!",
        ["celebration.care"] = "Harika bir ilk gün",
        ["celebration.care_reward"] = "+180 jeton · Cat Runner açıldı",
        ["celebration.play"] = "Haydi oynayalım",
        ["quests.title"] = "Mutlu bir yuvaya adım adım",
        ["quests.chapter_tab"] = "Yuva yolculuğu",
        ["quests.daily_tab"] = "Bugün",
        ["quests.refresh_daily"] = "Her gün yeni hedefler",
        ["quests.chapter"] = "Bölüm {0}",
        ["quests.claim"] = "Ödülü al",
        ["quests.claimed"] = "Alındı",
        ["quests.locked"] = "Henüz açık değil",
        ["quests.active"] = "Devam ediyor",
        ["quests.unavailable"] = "Sıradaki hedeflerin burada görünecek.",
        ["quests.wallet"] = "{0} jeton   ·   {1} bağ puanı   ·   {2} elmas",
        ["currency.coins"] = "jeton",
        ["currency.bond"] = "bağ puanı",
        ["return.title"] = "Yeniden hoş geldin!",
        ["return.continue"] = "Kedime dön",
        ["return.away"] = "{0} boyunca uzaktaydın.",
        ["return.water"] = "Biraz taze su kedini mutlu edecek.",
        ["return.food"] = "Kedin lezzetli bir öğüne hazır.",
        ["return.rest"] = "Rahat bir uyku kedine iyi gelecek.",
        ["return.nap"] = "Rahat bir uyku, enerjiyi %{0} artırdı.",
        ["return.missed"] = "Kedin seni özledi. Biraz birlikte vakit geçirelim.",
        ["shop.required"] = "Önce: {0}",
        ["shop.required_body"] = "{0} için {1} gerekiyor. Bu işlem önce gerekli eşyayı alır.",
        ["shop.requested"] = "Ardından {0} alabilirsin.",
        ["shop.room_purchase"] = "Sen ve kedin için yeni bir oda.",
        ["shop.cat_placement"] = "Aldıktan sonra bu kedi eşyası için yer seçebilirsin.",
        ["shop.confirm"] = "Satın almayı onayla",
        ["shop.confirm_body"] = "{0}, {1} elmas karşılığında alınsın mı?",
        ["shop.furniture_title"] = "{0} koleksiyonu",
        ["diamonds.title"] = "Biraz daha ışıltı",
        ["diamonds.subtitle"] = "Yuvan için uygun elmas paketini seç.",
        ["diamonds.units"] = "elmas",
        ["diamonds.unavailable"] = "Kullanılamıyor",
        ["diamonds.recommended"] = "Uygun paket",
        ["diamonds.store_unavailable"] = "Satın alma şu anda kullanılamıyor. Daha sonra tekrar dene.",
        ["diamonds.choose"] = "Bir paket seç. Fiyat ve ödeme cihazının mağazasında onaylanır.",
        ["diamonds.complete"] = "Elmasların hazır!",
        ["diamonds.failed"] = "Satın alma tamamlanamadı. Tekrar deneyebilirsin.",
        ["diamonds.connecting"] = "Cihazının mağazası bekleniyor…",
        ["diamonds.loading"] = "Fiyat yükleniyor…",
        ["diamonds.cancelled"] = "Satın alma iptal edildi. Elmas eklenmedi.",
        ["common.cancel"] = "Vazgeç",
        ["privacy.confirm.title"] = "Bulut hesabın silinsin mi?",
        ["privacy.confirm.body"] = "Bulut kaydın ve Cat Home giriş hesabın kalıcı olarak silinir. Bu işlem geri alınamaz. Cihazındaki yerel ilerleme korunur.",
        ["privacy.confirm.action"] = "Bulut hesabını sil",
        ["settings.group.sound"] = "Ses",
        ["settings.group.access"] = "Erişilebilirlik ve dil",
        ["settings.connected"] = "Bağlandı",
        ["settings.connect"] = "Google’a bağlan",
        ["cat.title"] = "Kedim",
        ["mycat.title"] = "Kedim",
        ["cat.subtitle"] = "Senin kedin, senin seçimin.",
        ["cat.appearance"] = "Görünüm",
        ["cat.name"] = "Kedinin adı",
        ["cat.coat"] = "Tüy rengi",
        ["cat.continue"] = "BU KEDİYLE DEVAM ET",
        ["cat.current"] = "Şu anki kedin",
        ["cat.preview"] = "Önizleme · Devam et ile kaydet",
        ["rooms.title"] = "Yuvam",
        ["rooms.subtitle"] = "Sekiz güzel oda.\nBir mutlu kedi.",
        ["rooms.hint"] = "Koleksiyonları tamamla, yeni odaları keşfet.",
        ["rooms.locked"] = "Kilitli",
        ["rooms.current"] = "Buradasın",
        ["rooms.ready"] = "Ziyarete hazır",
        ["rooms.unlock_hint"] = "Mağazadan açılabilir",
        ["rooms.unlock"] = "İncele",
        ["rooms.visit"] = "Git",
        ["rooms.progress"] = "{0} / {1} eşya evinde",
        ["rooms.current_hint"] = "Kedin şu anda {0} içinde.",
        ["home.hunger"] = "Tokluk",
        ["home.thirst"] = "Su",
        ["home.energy"] = "Enerji",
        ["home.level"] = "Seviye {0}",
        ["cloud.status.ready"] = "Google hesabın bağlı. Bulut kaydını kontrol etmek için eşitle.",
        ["shop.title"] = "Mağaza",
        ["shop.subtitle"] = "Yuvanı güzelleştiren küçük dokunuşlar.",
        ["shop.cat"] = "Kedi eşyaları",
        ["shop.room"] = "Mobilyalar",
        ["shop.home"] = "Odalar",
        ["shop.placement"] = "Evindeki hazır yerine eklenir.",
        ["shop.owned"] = "Evinde",
        ["shop.in_collection"] = "Koleksiyonda",
        ["shop.in_room"] = "Odada",
        ["shop.place"] = "Yerleştir",
        ["shop.cancel_placement"] = "Vazgeç",
        ["shop.progress"] = "{0} / {1} toplandı",
        ["shop.buy_coins"] = "{0} jeton ile al",
        ["shop.buy_diamonds"] = "{0} elmas ile al",
        ["shop.need_coins"] = "{0} jeton daha gerekli",
        ["common.not_now"] = "Şimdi değil",
        ["title.greeting.empty"] = "Kedin seni bekliyor",
        ["title.greeting.named"] = "{0} seni bekliyor",
        ["title.home.empty"] = "Yuvana\nhoş geldin.",
        ["title.home.named"] = "Yuvana\nhoş geldin.",
        ["title.play"] = "OYNA",
        ["title.continue"] = "Devam et",
        ["title.home_level"] = "Yuva seviyesi {0}",
        ["title.collection"] = "{0} / {1} • TOPLANDI",
        ["title.settings"] = "Ayarlar",
        ["title.credits"] = "Yapımcılar",
        ["title.quit"] = "Çıkış",
        ["title.new_game"] = "Yeni oyun",
        ["title.promise"] = "Birlikte güzel bir gün daha.",
        ["title.shortcuts"] = "MUTLU KÖŞENİ SEÇ",
        ["title.shop"] = "Mağaza",
        ["title.my_cat"] = "Kedim",
        ["title.rooms"] = "Odalar",
        ["title.games"] = "Oyunlar",
        ["title.after_tour"] = "TURDAN SONRA",
        ["credits.title"] = "Emek verenler",
        ["credits.body"] = "Kedi modelleri ve animasyonlar · Polyperfect\nOyun motoru · Unity\nArayüz yazı tipi · Fredoka\n\nKedine bir yuva açtığın için teşekkürler.",
        ["common.close"] = "Kapat",
        ["common.back"] = "GERİ",
        ["menu.quests"] = "Görevler",
        ["menu.main_menu"] = "Ana menü",
        ["settings.badge"] = "AYAR",
        ["settings.title"] = "Ayarlar",
        ["settings.subtitle"] = "Her şey sana uygun olsun.",
        ["settings.row.music"] = "Ev müziği",
        ["settings.row.sound"] = "Ev ses efektleri",
        ["settings.row.game_sound"] = "Mini oyun sesi",
        ["settings.row.haptics"] = "Titreşim",
        ["settings.row.reduced_motion"] = "Azaltılmış hareket",
        ["settings.row.language"] = "Dil",
        ["settings.row.account"] = "Hesabın",
        ["settings.privacy_data"] = "GİZLİLİK VE VERİ",
        ["settings.on"] = "AÇIK",
        ["settings.off"] = "KAPALI",
        ["language.english"] = "ENGLISH",
        ["language.turkish"] = "TÜRKÇE",
        ["new_game.title"] = "İlerleme sıfırlansın mı?",
        ["new_game.body"] = "JETONLAR, ODALAR, EŞYALAR, SEVİYELER VE SKORLAR SIFIRLANIR.\nELMASLAR, SATIN ALMA HAKLARI VE AYARLAR KORUNUR.",
        ["new_game.cancel"] = "VAZGEÇ",
        ["new_game.confirm"] = "İlerlemeyi sıfırla",
        ["new_game.failed"] = "YENİ OYUN BAŞLATILAMADI. MEVCUT KAYDIN GÜVENDE.",
        ["account.choice.title"] = "Yuvanı güvende tut",
        ["account.choice.subtitle"] = "İlerlemeni cihazlar arasında korumak için Google’a bağlan.",
        ["account.google.action"] = "GOOGLE İLE GİRİŞ YAP",
        ["account.google.benefit"] = "BULUT KAYDI • ÇEVRİMİÇİ SIRALAMA • BAŞKA CİHAZDA DEVAM",
        ["account.google.success"] = "GOOGLE HESABI BAĞLANDI.",
        ["account.google.cancelled"] = "GİRİŞ İPTAL EDİLDİ. MEVCUT KAYDIN GÜVENDE.",
        ["account.google.unavailable"] = "GOOGLE GİRİŞİ HAZIR DEĞİL. BAĞLANTIYI VEYA HESAP KURULUMUNU KONTROL ET.",
        ["account.google.already_linked"] = "BU HESABIN ZATEN BİR CAT HOME'U VAR. EN GÜNCEL KAYIT OTOMATİK YÜKLENECEK.",
        ["account.guest.action"] = "MİSAFİR OLARAK DEVAM ET",
        ["account.guest.note"] = "Misafir ilerlemesi bu cihazda saklanır.",
        ["account.status.none"] = "SEÇ",
        ["account.status.guest"] = "MİSAFİR",
        ["account.status.guest_offline"] = "MİSAFİR • ÇEVRİMDIŞI",
        ["account.status.google"] = "GOOGLE BAĞLI",
        ["account.status.connecting"] = "BAĞLANIYOR...",
        ["privacy.title"] = "Gizlilik ve verilerin",
        ["privacy.policy"] = "GİZLİLİK POLİTİKASI",
        ["privacy.delete_info"] = "HESAP SİLME BİLGİSİ",
        ["privacy.data_requests"] = "VERİ TALEPLERİ",
        ["privacy.sync_now"] = "ŞİMDİ EŞİTLE",
        ["privacy.delete_cloud"] = "BULUT HESABINI VE VERİLERİ SİL",
        ["privacy.delete_confirm"] = "SİLMEK İÇİN TEKRAR DOKUN",
        ["privacy.delete_note"] = "YEREL MİSAFİR KAYDIN BU CİHAZDA KALIR. BULUT VERİLERİN VE OYUNCU HESABIN KALICI OLARAK SİLİNİR.",
        ["privacy.unity_portal"] = "UNITY OYUNCU HESABI PORTALI",
        ["privacy.guest_status"] = "BULUT KAYDI VE HESAP SİLME İÇİN GOOGLE İLE GİRİŞ YAP.",
        ["cloud.status.offline"] = "BULUT KAYDI İÇİN GOOGLE GİRİŞİ GEREKLİ.",
        ["cloud.status.syncing"] = "CİHAZ VE BULUT KAYDI EŞİTLENİYOR...",
        ["cloud.status.empty"] = "EŞİTLENECEK YEREL KAYIT HAZIR DEĞİL.",
        ["cloud.status.synced"] = "CİHAZ VE BULUT KAYDI GÜNCEL.",
        ["cloud.status.invalid"] = "BULUT KAYDI OKUNAMADI. CİHAZ KAYDIN GÜVENDE.",
        ["cloud.status.unavailable"] = "BULUT KAYDI ŞİMDİLİK KULLANILAMIYOR. CİHAZ KAYDIN GÜVENDE.",
        ["cloud.status.cloud_applied"] = "BULUT KAYDI BU CİHAZA YÜKLENDİ.",
        ["cloud.status.deleting"] = "BULUT VERİLERİ VE OYUNCU HESABI SİLİNİYOR...",
        ["cloud.status.deleted"] = "BULUT VERİLERİ VE OYUNCU HESABI SİLİNDİ. MİSAFİR OLARAK DEVAM EDİLİYOR.",
        ["cloud.status.delete_failed"] = "SİLME TAMAMLANAMADI. BAŞKA BİR DEĞİŞİKLİK YAPILMADI."
    };

    private static bool initialized;
    private static GameLanguage current;

    public static event Action Changed;

    public static GameLanguage Current
    {
        get
        {
            EnsureInitialized();
            return current;
        }
    }

    public static GameLanguage ResolveInitialLanguage(SystemLanguage systemLanguage) =>
        systemLanguage == SystemLanguage.Turkish
            ? GameLanguage.Turkish
            : GameLanguage.English;

    public static void SetLanguage(GameLanguage language)
    {
        EnsureInitialized();
        if (current == language && PlayerPrefs.HasKey(PlayerPrefsKey))
            return;
        current = language;
        PlayerPrefs.SetInt(PlayerPrefsKey, (int)language);
        PlayerPrefs.Save();
        Changed?.Invoke();
    }

    public static void Toggle() => SetLanguage(
        Current == GameLanguage.English ? GameLanguage.Turkish : GameLanguage.English);

    public static string Text(string key)
    {
        EnsureInitialized();
        Dictionary<string, string> table = current == GameLanguage.Turkish ? Turkish : English;
        if (!string.IsNullOrEmpty(key) && table.TryGetValue(key, out string value))
            return value;
        // Keys are not user text. A missing translation must never expose an
        // English fallback or an internal identifier in the Turkish UI.
        return current == GameLanguage.Turkish ? Turkish["localization.unavailable"] : English["localization.unavailable"];
    }

    public static string Format(string key, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, Text(key), args);

    private static void EnsureInitialized()
    {
        if (initialized)
            return;
        int fallback = (int)ResolveInitialLanguage(Application.systemLanguage);
        current = (GameLanguage)Mathf.Clamp(
            PlayerPrefs.GetInt(PlayerPrefsKey, fallback),
            (int)GameLanguage.English,
            (int)GameLanguage.Turkish);
        initialized = true;
    }

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
    private static void ResetRuntimeState()
    {
        initialized = false;
        current = GameLanguage.English;
        Changed = null;
    }
}
